# Generated by Django 6.0.6 on 2026-06-07 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WM', 'Wm'), ('DE', 'De'), ('Shell', 'Shell'), ('Terminal', 'Terminal'), ('NVim/Vim', 'Nvim Vim'), ('Emacs', 'Emacs'), ('VSCode', 'Vscode'), ('Bar', 'Bar'), ('Compositor', 'Compositor'), ('Launcher', 'Launcher'), ('Fetch', 'Fetch'), ('Arch', 'Arch'), ('Debian', 'Debian'), ('NixOS', 'Nixos'), ('Fedora', 'Fedora'), ('Mint', 'Mint'), ('Gentoo', 'Gentoo'), ('Ubuntu', 'Ubuntu')], max_length=20), blank=True, default=list)),
            ],
        ),
    ]
