# Generated by Django 6.0.6 on 2026-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
