# Generated by Django 6.0.6 on 2026-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='configs/'),
        ),
    ]
